name: Generate build artifactories

on:
  push:
    branches:
      - 'master'
      - 'develop'
  pull_request:
    branches:
      - 'master'
      - 'develop'

jobs:
  apk:
    name: Generate Artifactory
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v3
      - name: set up JDK 11
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: 11
      - name: Build debug APK
        run: bash ./gradlew assembleDebug --stacktrace
      - name: Upload APK
        uses: actions/upload-artifact@v3
        with:
          name: app
          path: app/build/outputs/apk/debug/app-debug.apk
          retention-days: 10